#include <MyLogger/Logger.hpp>

#if 1
// Define some information needed by MyLogger
namespace project
{
  static Info info(
    // Compiled in debug or released mode
    true,
    // Project name used for logs and GUI.
    "MyLoggerExample",
    // Major version of project
    0u,
    // Minor version of project
    1u,
    // git SHA1
    "3a2b3791f7cca5188259ae01d39c6194d2708c9f",
    // git branch
    "master",
    // Pathes where default project resources have been installed
    // (when called  by the shell command: sudo make install).
    "/home/qq/MyGitHub/MyLogger:/usr/share/MyLogger/0.1",
    // Location for storing temporary files
    "/tmp/MyLogger/",
    // Give a name to the default project log file.
    "MyLoggerExample.log",
    // Define the full path for the project.
    "/tmp/MyLogger/MyLoggerExample.log"
  );
}
#else
// Note: this structure is auto-generated by
// https://github.com/Lecrapouille/MyMakefile
// inside the $(BUILD) folder and that can be
// included with:
#  include "project_info.hpp"
#endif

// Compilation: g++ --std=c++11 main.cpp -o app `pkg-config --cflags --libs mylogger`
int main()
{
    CONFIG_LOG(project::info);
    LOGI("An information %s %d", "the info", 42);
    LOGD("A debug %s", "the debug"); // Displayed only if -UNDEBUG is passed to compiler
    LOGW("A warning %s", "the warning");
    LOGF("A failure %s", "the failure");

    return 0;
}
