name: Non regression tests for MyLogger
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  non_regression_linux:
    name: Non regression tests on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config lcov libdw-dev bc libsfml-dev
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile MyLogger
        run: |
          make download-external-libs
          make -j`nproc --all`
          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          make -j`nproc --all`
          ./build/MyLogger-UnitTest

  non_regression_macos:
    name: Non regression tests on MacOS X
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          brew install pkg-config sfml
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile MyLogger
        run: |
          make download-external-libs
          make -j`sysctl -n hw.logicalcpu`
      - name: Do non regression tests
        run: |
          cd tests
          make -j`sysctl -n hw.logicalcpu`
          ./build/MyLogger-UnitTest
